---
start_sequence:
- { component_name: 'NATS', job_name_prefix: 'nats'}
- { component_name: 'consul', job_name_prefix: 'consul_server'}
- { component_name: 'etcd', job_name_prefix: 'etcd_server'}
- { component_name: 'Diego Database', job_name_prefix: 'diego_database'}
- { component_name: 'NFS Server', job_name_prefix: 'nfs_server'}
- { component_name: 'Router', job_name_prefix: 'router'}
- { component_name: 'MySQL Proxy', job_name_prefix: 'mysql_proxy'}
- { component_name: 'MySQL Server', job_name_prefix: 'mysql'}
- { component_name: 'Cloud Controller Database', job_name_prefix: 'ccdb'}
- { component_name: 'UAA Database', job_name_prefix: 'uaadb'}
- { component_name: 'Apps Manager Database', job_name_prefix: 'consoledb'}
- { component_name: 'Cloud Controller', job_name_prefix: 'cloud_controller'}
- { component_name: 'HAProxy', job_name_prefix: 'ha_proxy'}
- { component_name: 'Health Manager', job_name_prefix: 'health_manager'}
- { component_name: 'Clock Global', job_name_prefix: 'clock_global'}
- { component_name: 'Cloud Controller Worker', job_name_prefix: 'cloud_controller_worker'}
- { component_name: 'Collector', job_name_prefix: 'collector'}
- { component_name: 'UAA', job_name_prefix: 'uaa'}
- { component_name: 'Diego Brain', job_name_prefix: 'diego_brain'}
- { component_name: 'Diego Cell', job_name_prefix: 'diego_cell'}
- { component_name: 'Doppler Server', job_name_prefix: 'doppler'}
- { component_name: 'Loggregator Traffic Controller', job_name_prefix: 'loggregator_trafficcontroller'}

stop_sequence:
- { component_name: 'Loggregator Traffic Controller', job_name_prefix: 'loggregator_trafficcontroller'}
- { component_name: 'Doppler Server', job_name_prefix: 'doppler'}
- { component_name: 'Diego Cell', job_name_prefix: 'diego_cell'}
- { component_name: 'Diego Brain', job_name_prefix: 'diego_brain'}
- { component_name: 'UAA', job_name_prefix: 'uaa'}
- { component_name: 'Collector', job_name_prefix: 'collector'}
- { component_name: 'Cloud Controller Worker', job_name_prefix: 'cloud_controller_worker'}
- { component_name: 'Clock Global', job_name_prefix: 'clock_global'}
- { component_name: 'Health Manager', job_name_prefix: 'health_manager'}
- { component_name: 'HAProxy', job_name_prefix: 'ha_proxy'}
- { component_name: 'Cloud Controller', job_name_prefix: 'cloud_controller'}
- { component_name: 'Apps Manager Database', job_name_prefix: 'consoledb'}
- { component_name: 'UAA Database', job_name_prefix: 'uaadb'}
- { component_name: 'Cloud Controller Database', job_name_prefix: 'ccdb'}
- { component_name: 'MySQL Server', job_name_prefix: 'mysql'}
- { component_name: 'MySQL Proxy', job_name_prefix: 'mysql_proxy'}
- { component_name: 'Router', job_name_prefix: 'router'}
- { component_name: 'NFS Server', job_name_prefix: 'nfs_server'}
- { component_name: 'Diego Database', job_name_prefix: 'diego_database'}
- { component_name: 'etcd', job_name_prefix: 'etcd_server'}
- { component_name: 'consul', job_name_prefix: 'consul_server'}
- { component_name: 'NATS', job_name_prefix: 'nats'}
